# web-core image is meant to be used only by our safe-infrastructure repository

name: Deploy to Dockerhub

on:
  pull_request:
    branches:
      - metis
  push:
    branches:
      - metis
  release:
    types: [released]

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/metis' || (github.event_name == 'release' && github.event.action == 'released') || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Add secrets to .env
        run: |-
          echo "NEXT_PUBLIC_SOCIAL_WALLET_OPTIONS_STAGING=${{ secrets.SOCIAL_WALLET_OPTIONS }}" >> .env &&
          echo "NEXT_PUBLIC_SOCIAL_WALLET_OPTIONS_PRODUCTION=${{ secrets.SOCIAL_WALLET_OPTIONS }}" >> .env
      - name: Deploy Dev
        if: github.ref == 'refs/heads/metis'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: metissafe/safe-wallet-web:dev
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy PR Image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: metissafe/safe-wallet-web:pr-${{ github.event.number }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy Tag
        if: (github.event_name == 'release' && github.event.action == 'released')
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            metissafe/safe-wallet-web:${{ github.event.release.tag_name }}
            metissafe/safe-wallet-web:latest
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
